version: 2

sources:
  - name: s3_people
    tables:
      - name: people
        description: "This table contains data from an S3 CSV file."
        external:
          location: "s3://uvasds-systems/data/people.csv"
          file_format: "csv"
        columns:
          - name: id
            data_type: int64 
            description: "Unique identifier for each person"
          - name: first_name
            data_type: varchar
            description: "Person's first name"
          - name: last_name
            data_type: varchar
            description: "Person's last name"
          - name: email
            data_type: varchar
            description: "Person's email address"
          - name: ip_address
            data_type: varchar
            description: "Person's IP address"
          - name: dob
            data_type: date
            description: "Person's date of birth"

models:
  - name: clean_people
    description: "Cleaned people data with missing last_name or dob values removed"
    columns:
      - name: id
        data_type: int64
        description: "Unique identifier for each person"
        tests:
          - unique
          - not_null
      - name: first_name
        data_type: varchar
        description: "Person's first name"
      - name: last_name
        data_type: varchar
        description: "Person's last name"
        tests:
          - not_null
      - name: email
        data_type: varchar
        description: "Person's email address"
      - name: ip_address
        data_type: varchar
        description: "Person's IP address"
      - name: dob
        data_type: date
        description: "Person's date of birth"
        tests:
          - not_null